'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace XtraPivotGrid_XMLA.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As XtraPivotGrid_XMLA.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New XtraPivotGrid_XMLA.Properties.Settings())), XtraPivotGrid_XMLA.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return XtraPivotGrid_XMLA.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
